-- 0093: add papers.zotero_citation_key (consumed by zotero push/resync)
--
-- WHY: zotero_service.py fetches the Better BibTeX citation key from the local
-- BBT plugin after a successful push and writes it via
-- UPDATE papers SET zotero_citation_key = $1 WHERE id = $2
-- Likewise, routers/zotero.py SELECTs it for the Zotero status endpoint.
-- The column was missing from init.sql, causing a 500 on any push or resync.
--
-- SAFETY: IF NOT EXISTS makes this idempotent — safe on a fresh install where
-- init.sql already creates the column.
ALTER TABLE public.papers ADD COLUMN IF NOT EXISTS zotero_citation_key text;
