#!/usr/bin/env bash
# Export service requirements and constraints from pyproject.toml/uv.lock.
#
# The root pyproject dependency groups are canonical. Docker still installs
# with pip for small images and simple build layers:
#
# - requirements files contain direct, human-auditable service dependencies
# - constraints files contain lock-derived transitive pins with SHA-256 hashes
#   for supply-chain hardening (pip install --require-hashes in Dockerfiles)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_ROOT="${OUTPUT_ROOT:-$ROOT_DIR}"

write_direct_requirements() {
  ROOT_DIR="$ROOT_DIR" OUTPUT_ROOT="$OUTPUT_ROOT" python3 - <<'PY'
from __future__ import annotations

import os
import tomllib
from pathlib import Path

root = Path(os.environ["ROOT_DIR"])
output_root = Path(os.environ["OUTPUT_ROOT"])
groups = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))[
    "dependency-groups"
]

outputs = {
    "paper-ingestion": "services/paper_ingestion/requirements.txt",
    "paper-ingestion-optional": "services/paper_ingestion/requirements-optional.txt",
    "learning-engine": "services/learning_engine/requirements.txt",
    "telegram-bot": "services/telegram_bot/requirements.txt",
}

HEADER = (
    "# Generated by scripts/export-service-requirements.sh; do not edit directly.\n"
    "# Update pyproject.toml dependency groups, then rerun the export script.\n"
)


def expand_group(name: str, *, seen: set[str] | None = None) -> list[str]:
    """Inline `{include-group = "..."}` references recursively.

    Without expansion, ``pip install -r services/<svc>/requirements.txt`` would
    silently miss `jarvis_common`'s `cryptography` and `pydantic-settings` deps
    (the Dockerfiles install jarvis_common transitively, but the requirements
    files claim to be the standalone shape). Cycles short-circuit defensively.
    """
    if seen is None:
        seen = set()
    if name in seen:
        return []
    seen = seen | {name}
    out: list[str] = []
    for dep in groups.get(name, []):
        if isinstance(dep, str):
            out.append(dep)
        elif isinstance(dep, dict) and "include-group" in dep:
            out.extend(expand_group(dep["include-group"], seen=seen))
    return out


for group, relative_output in outputs.items():
    output_path = output_root / relative_output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    deduped: list[str] = []
    seen_pkgs: set[str] = set()
    for dep in expand_group(group):
        if dep not in seen_pkgs:
            seen_pkgs.add(dep)
            deduped.append(dep)
    output_path.write_text(HEADER + "\n".join(deduped) + "\n", encoding="utf-8")
PY
}

export_constraints() {
  local group="$1"
  local output="$2"
  local output_path="$OUTPUT_ROOT/$output"

  mkdir -p "$(dirname "$output_path")"
  local tmp_output
  tmp_output="$(mktemp)"
  (
    cd "$ROOT_DIR"
    uv export \
      --frozen \
      --format requirements.txt \
      --only-group "$group" \
      --no-annotate \
      --no-header \
      --no-emit-project \
      --output-file "$tmp_output" \
      >/dev/null
  )
  {
    echo "# Generated by scripts/export-service-requirements.sh; do not edit directly."
    echo "# Update uv.lock via uv lock, then rerun the export script."
    cat "$tmp_output"
  } >"$output_path"
  rm -f "$tmp_output"
}

write_direct_requirements
export_constraints "paper-ingestion" "services/paper_ingestion/constraints.txt"
export_constraints "paper-ingestion-optional" "services/paper_ingestion/constraints-optional.txt"
export_constraints "learning-engine" "services/learning_engine/constraints.txt"
export_constraints "telegram-bot" "services/telegram_bot/constraints.txt"
