#!/usr/bin/env bash
# Export service requirements and constraints from pyproject.toml/uv.lock.
#
# The root pyproject dependency groups are canonical. Docker still installs
# with pip for small images and simple build layers:
#
# - requirements files contain direct, human-auditable service dependencies
# - constraints files contain lock-derived transitive pins with SHA-256 hashes
#   for supply-chain hardening (pip install --require-hashes in Dockerfiles)
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_ROOT="${OUTPUT_ROOT:-$ROOT_DIR}"

write_direct_requirements() {
  ROOT_DIR="$ROOT_DIR" OUTPUT_ROOT="$OUTPUT_ROOT" python3 - <<'PY'
from __future__ import annotations

import os
import re
import tomllib
from pathlib import Path

root = Path(os.environ["ROOT_DIR"])
output_root = Path(os.environ["OUTPUT_ROOT"])
groups = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))[
    "dependency-groups"
]

outputs = {
    "platform-api": "services/platform_api/requirements.txt",
    "paper-ingestion": "services/paper_ingestion/requirements.txt",
    "paper-ingestion-optional": "services/paper_ingestion/requirements-optional.txt",
    "learning-engine": "services/learning_engine/requirements.txt",
    "telegram-bot": "services/telegram_bot/requirements.txt",
}

HEADER = (
    "# Generated by scripts/export-service-requirements.sh; do not edit directly.\n"
    "# Update pyproject.toml dependency groups, then rerun the export script.\n"
)


def expand_group(name: str, *, seen: set[str] | None = None) -> list[str]:
    """Inline `{include-group = "..."}` references recursively.

    Without expansion, ``pip install -r services/<svc>/requirements.txt`` would
    silently miss `jarvis_common`'s `cryptography` and `pydantic-settings` deps
    (the Dockerfiles install jarvis_common transitively, but the requirements
    files claim to be the standalone shape). Cycles short-circuit defensively.
    """
    if seen is None:
        seen = set()
    if name in seen:
        return []
    seen = seen | {name}
    out: list[str] = []
    for dep in groups.get(name, []):
        if isinstance(dep, str):
            out.append(dep)
        elif isinstance(dep, dict) and "include-group" in dep:
            out.extend(expand_group(dep["include-group"], seen=seen))
    return out


def canonical_name(spec: str) -> str:
    """Return the PEP 503 canonical distribution name from a requirement spec."""
    match = re.match(r"[A-Za-z0-9._-]+", spec)
    if not match:
        raise SystemExit(f"cannot read a distribution name from requirement {spec!r}")
    return re.sub(r"[-_.]+", "-", match.group(0)).lower()


def without_extras(spec: str) -> str:
    """Return the spec with its extras removed, so `x[a]>=1` and `x>=1` compare equal."""
    return re.sub(r"\[[^\]]*\]", "", spec, count=1)


def extras_of(spec: str) -> frozenset[str]:
    """Return the extras a spec asks for, so `x[a,b]>=1` gives ``{"a", "b"}``."""
    match = re.search(r"\[([^\]]*)\]", spec)
    if not match:
        return frozenset()
    return frozenset(part.strip() for part in match.group(1).split(",") if part.strip())


for group, relative_output in outputs.items():
    output_path = output_root / relative_output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    # Deduplicate by distribution name rather than by the whole spec string. One
    # group may ask for `uvicorn>=0.30.0` while a group it includes asks for
    # `uvicorn[standard]>=0.30.0`; those are different strings, so a string-keyed
    # dedup emits both and the file carries two spec lines for one package. Keep
    # the extras-bearing spec, which is the stronger requirement. Two specs whose
    # version constraints actually differ are a conflict in pyproject.toml, so
    # stop rather than silently choose one.
    deduped: list[str] = []
    slot_by_name: dict[str, int] = {}
    for dep in expand_group(group):
        name = canonical_name(dep)
        if name not in slot_by_name:
            slot_by_name[name] = len(deduped)
            deduped.append(dep)
            continue
        kept = deduped[slot_by_name[name]]
        if without_extras(kept) != without_extras(dep):
            raise SystemExit(
                f"{relative_output}: conflicting requirements for {name!r}: "
                f"{kept!r} and {dep!r} - reconcile them in pyproject.toml"
            )
        kept_extras, dep_extras = extras_of(kept), extras_of(dep)
        # Two groups asking for the same package with DIFFERENT extras is not a
        # stronger-vs-weaker pair, so there is no "keep the stronger" answer:
        # emitting either one silently drops the other group's extra, and
        # emitting the union would no longer match what uv resolved. Stop.
        if kept_extras and dep_extras and kept_extras != dep_extras:
            raise SystemExit(
                f"{relative_output}: {name!r} is requested with different extras: "
                f"{kept!r} and {dep!r} - reconcile them in pyproject.toml"
            )
        if dep_extras > kept_extras:
            deduped[slot_by_name[name]] = dep
    output_path.write_text(HEADER + "\n".join(deduped) + "\n", encoding="utf-8")
PY
}

export_constraints() {
  local group="$1"
  local output="$2"
  shift 2
  # Remaining args are pip directives (e.g. --extra-index-url) emitted after
  # the header; uv export does not embed index URLs in requirements format.
  local output_path="$OUTPUT_ROOT/$output"

  mkdir -p "$(dirname "$output_path")"
  local tmp_output
  tmp_output="$(mktemp)"
  (
    cd "$ROOT_DIR"
    uv export \
      --frozen \
      --format requirements.txt \
      --only-group "$group" \
      --no-annotate \
      --no-header \
      --no-emit-project \
      --output-file "$tmp_output" \
      >/dev/null
  )
  {
    echo "# Generated by scripts/export-service-requirements.sh; do not edit directly."
    echo "# Update uv.lock via uv lock, then rerun the export script."
    for directive in "$@"; do
      printf '%s\n' "$directive"
    done
    cat "$tmp_output"
  } >"$output_path"
  rm -f "$tmp_output"
}

write_direct_requirements
export_constraints "paper-ingestion" "services/paper_ingestion/constraints.txt"
# CPU torch flavor: same dependency set, torch from the PyTorch CPU index
# (no nvidia-*/triton). Selected in the Dockerfile via TORCH_VARIANT=cpu.
export_constraints "paper-ingestion-cpu" "services/paper_ingestion/constraints-cpu.txt" \
  "--extra-index-url https://download.pytorch.org/whl/cpu"
export_constraints "paper-ingestion-optional" "services/paper_ingestion/constraints-optional.txt"
# CPU flavor of the reranker extras: torch from the PyTorch CPU index so a
# TORCH_VARIANT=cpu build with INSTALL_OPTIONAL=true reuses the +cpu torch
# already in the base image instead of the ~3.7 GB nvidia-*/triton set.
export_constraints "paper-ingestion-optional-cpu" "services/paper_ingestion/constraints-optional-cpu.txt" \
  "--extra-index-url https://download.pytorch.org/whl/cpu"
export_constraints "platform-api" "services/platform_api/constraints.txt"
export_constraints "learning-engine" "services/learning_engine/constraints.txt"
export_constraints "telegram-bot" "services/telegram_bot/constraints.txt"
