"""Weekly research summary generator.

Groups recent papers by topic and synthesizes cross-paper themes
using LLM analysis for each topic cluster.

Only papers the user has actively engaged with are included:
- Library UI engagement: paper_user_state.starred = TRUE or state IN ('reading', 'done')
- Pulse card engagement: recommendation_feedback.signal = 'positive'
  AND source IN ('pulse_thumbs', 'dismiss_combined') within the same window

This is the Model C (Complementary) guarantee: Weekly Summary reflects
what the user actually engaged with, not the full Pulse candidate firehose.

Theme verification: each theme (with ``[Paper N]`` reference markers stripped)
is fuzzy-matched against per-paper ``title + summary_brief`` chunks via
``QuoteVerifier``, accepted at ``WEEKLY_SUPPORT_FUZZY`` partial_ratio support.
Calibration (2026-06-12, real stored 4-paper corpus, themes generated by the
live smart model with this module's exact prompt): real themes scored
46.6 / 56.0 / 71.0; five hand-fabricated plausible-but-unsupported themes
scored 48.4-51.0 (the in-domain noise floor). The bar of 54 splits the
fabricated band (max 51.0) from the lexically supported themes (min 56.0)
with margin on both sides. Cross-paper abstractions scoring below the noise
floor stay unverified — lowering the bar to admit them would also admit
every fabrication.
"""

from __future__ import annotations

import asyncio
import logging
import re
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING

import asyncpg
from jarvis_common import get_smart_model
from jarvis_common.llm_client import (
    LLM_TIMEOUT_DEFAULT,
    ChatCompletionOptions,
    call_llm_structured,
    observe,
)
from jarvis_common.prompt_safety import safe_for_prompt, wrap_delimited
from jarvis_common.time_utils import utc_now_iso
from jarvis_common.verify import DictChunk, QuoteVerifier

from paper_ingestion.weekly_summary_models import ThemeOutput, WeeklyDigestOutput

if TYPE_CHECKING:
    import openai


logger = logging.getLogger(__name__)

# Support bar for theme verification (fuzz.partial_ratio, 0-100).
# Calibrated against real stored summaries + live smart-model themes — see
# the module docstring for the measured positive/negative bands.
WEEKLY_SUPPORT_FUZZY = 54

# Matches the prompt-mandated paper reference markers ("[Paper 1]", "[Paper 12]").
# Anchored to that exact shape so legitimate bracketed content in theme text
# (e.g. "[CLS]", "[2026]") survives.
_PAPER_REF_RE = re.compile(r"\s*\[Paper\s+\d+\]", re.IGNORECASE)


def _theme_supported(
    verifier: QuoteVerifier,
    theme_text: str,
    corpus: str,
    chunks: list[DictChunk],
) -> tuple[bool, float | None]:
    """Fuzzy-verify *theme_text* against the per-paper corpus chunks.

    Strips ``[Paper N]`` markers first (they depress partial_ratio), then
    accepts either a verbatim QuoteVerifier match or a fuzzy match at
    ``WEEKLY_SUPPORT_FUZZY`` or above.  Returns ``(supported, match_score)``
    where ``match_score`` is the best 0.0-1.0 fuzzy score (``None`` if no
    overlap at all).
    """
    stripped = _PAPER_REF_RE.sub("", theme_text).strip()
    result = verifier.verify_quote(stripped, corpus, chunks)
    supported = result.verified or (
        result.match_score is not None and result.match_score * 100 >= WEEKLY_SUPPORT_FUZZY
    )
    return supported, result.match_score


_SYSTEM_WEEKLY_DIGEST = (
    "You are a research digest assistant. "
    "Analyze the papers provided in the <topic> and <papers> blocks and identify "
    "3-5 key themes or findings that emerge across them. "
    "For each theme: state it clearly in one sentence, reference supporting papers "
    "by their number [Paper N], and note any contradictions or open questions. "
    "Respond in JSON format: "
    '{"themes": [{"theme": "One-sentence theme description", '
    '"supporting_papers": [1, 3], "notes": "Optional context"}], '
    '"summary": "2-3 sentence overview of the topic\'s state this week"}'
)


@observe()
async def generate_weekly_summary(
    db_pool: asyncpg.Pool,
    verifier: QuoteVerifier,
    days: int = 7,
    user_id: int | None = None,
    openai_client: openai.AsyncOpenAI | None = None,
) -> dict:
    """Generate per-topic digests for papers the user engaged with in the lookback window.

    Only papers with active user engagement are included (Model C — Complementary):
    - Library UI: paper_user_state.starred = TRUE or state IN ('reading', 'done')
    - Pulse cards: recommendation_feedback.signal = 'positive' AND source IN
      ('pulse_thumbs', 'dismiss_combined') within the same window

    Papers passively surfaced by Pulse but never acted on are excluded,
    preventing the Weekly Summary from becoming a noise-generator.

    Each topic that meets the >=2 paper threshold produces one child
    ``generation`` span via ``call_llm_structured``; the outer ``@observe()``
    collects them all under a single ``generate_weekly_summary`` trace.

    Parameters
    ----------
    user_id:
        When provided, restricts ``paper_user_state`` and ``recommendation_feedback``
        lookups to the given user.  ``None`` (default) aggregates across all
        users, preserving backwards-compatible global behaviour.
    openai_client:
        Instructor-patched ``openai.AsyncOpenAI`` client for structured calls.
        When provided, ``call_llm_structured`` is used.  Pass
        ``app.state.openai_client`` from the service lifespan.
    """
    if openai_client is None:
        raise RuntimeError(
            "openai_client is required for weekly summary generation; "
            "pass app.state.openai_client (set by the service lifespan)"
        )

    cutoff = datetime.now(UTC) - timedelta(days=days)

    # asyncpg.Pool has no .fetch() method — must acquire a connection first.
    async with db_pool.acquire() as conn:
        smart_model = get_smart_model()
        rows = await conn.fetch(
            """
            SELECT p.id, p.title, p.url, p.published_date, p.authors,
                   t.name as topic_name, t.id as topic_id,
                   pt.relevance_score,
                   ps.summary_brief, ps.confidence
            FROM papers p
            JOIN paper_topics pt ON p.id = pt.paper_id
            JOIN topics t ON pt.topic_id = t.id
            LEFT JOIN paper_summaries ps
                ON p.id = ps.paper_id AND ps.user_id IS NOT DISTINCT FROM $2
            WHERE p.created_at >= $1
              AND (
                  EXISTS (
                      SELECT 1 FROM paper_user_state pus
                      WHERE pus.paper_id = p.id
                        AND (
                            COALESCE(pus.starred, FALSE)
                            OR pus.state IN ('reading', 'done')
                        )
                        AND pus.user_id IS NOT DISTINCT FROM $2
                  )
                  OR
                  EXISTS (
                      SELECT 1 FROM recommendation_feedback rf
                      WHERE rf.paper_id = p.id
                        AND rf.signal = 'positive'
                        AND rf.source IN ('pulse_thumbs', 'dismiss_combined')
                        AND rf.created_at >= $1
                        AND rf.user_id IS NOT DISTINCT FROM $2
                  )
              )
            ORDER BY t.name, pt.relevance_score DESC NULLS LAST
            """,
            cutoff,
            user_id,
        )

    # Empty-state honesty: short-circuit without calling the LLM.
    if not rows:
        logger.info(
            "weekly_summary: no engaged papers in the last %d days — skipping LLM synthesis",
            days,
        )
        return {
            "topics": [],
            "total_papers": 0,
            "period_start": cutoff.isoformat(),
            "period_end": utc_now_iso(),
            "message": (
                "No engaged papers in the last 7 days. "
                "Read or save some papers to see your weekly summary."
            ),
        }

    topics: dict[str, dict] = {}
    for row in rows:
        topic_name = row["topic_name"]
        if topic_name not in topics:
            topics[topic_name] = {"name": topic_name, "papers": []}
        topics[topic_name]["papers"].append(dict(row))

    result_topics: list[dict] = []
    total_papers: set[int] = set()

    for topic_name, topic_data in topics.items():
        papers = topic_data["papers"]
        total_papers.update(p["id"] for p in papers)

        papers_context = ""
        for i, p in enumerate(papers[:10], 1):
            brief = p.get("summary_brief") or p.get("title", "")
            papers_context += f"\n[Paper {i}]: {p['title']}\n  Summary: {brief[:300]}\n"

        themes: list[ThemeOutput] = []
        safe_topic = safe_for_prompt(topic_name, mode="escape")
        summary = f"{len(papers)} papers on {safe_topic} this week."

        if len(papers) >= 2:
            topic_block, _ = wrap_delimited("topic", topic_name)
            papers_block, _ = wrap_delimited("papers", papers_context)
            try:
                llm_data = await call_llm_structured(
                    openai_client,  # type: ignore[arg-type]
                    response_model=WeeklyDigestOutput,
                    prompt=(
                        f"Analyze these {len(papers[:10])} papers."
                        f"\n\n{topic_block}\n\n{papers_block}"
                    ),
                    options=ChatCompletionOptions(
                        model=smart_model,
                        system=_SYSTEM_WEEKLY_DIGEST,
                        max_tokens=600,
                        temperature=0.2,
                        timeout=LLM_TIMEOUT_DEFAULT,
                    ),
                )
                # Keep ThemeOutput instances; convert to dicts only at response boundary.
                themes = llm_data.themes
                summary = llm_data.summary
            except Exception:
                # weekly_summary generation degrades to the default summary if synthesis fails.
                # pydantic.ValidationError is caught here (no special handling needed).
                logger.exception("LLM weekly_summary generation failed for topic %s", topic_name)

        top_papers = [
            {
                "id": p["id"],
                "title": p["title"],
                "url": p["url"],
                "confidence": p.get("confidence"),
                "relevance_score": p.get("relevance_score"),
            }
            for p in papers[:5]
        ]

        # Verify each theme against per-paper title+summary_brief chunks built
        # from the rows already in memory (no extra DB fetches — this runs in a
        # rate-limited synchronous GET).  Cheap fuzzy match (~ms per theme),
        # ephemeral, not persisted.  Each theme dict in `themes` carries
        # `verified` (bool) and `verification_reason` (str|None) so the
        # frontend's VerificationBadge renders inline next to each theme.
        # `verified_themes` / `unverified_themes` split lists hold the same
        # dicts, kept for backward compatibility with consumers that still
        # rely on them.
        annotated_themes: list[dict] = []
        verified_themes: list[dict] = []
        unverified_themes: list[dict] = []
        if themes:
            chunks: list[DictChunk] = []
            corpus_parts: list[str] = []
            for p in papers[:10]:
                title = p.get("title") or ""
                brief = p.get("summary_brief") or ""
                paper_text = f"{title} {brief}".strip()
                if paper_text:
                    chunks.append(
                        DictChunk({"id": p["id"], "content": paper_text, "page_number": None})
                    )
                    corpus_parts.append(paper_text)
            corpus = " ".join(corpus_parts)

            for theme in themes:
                # Attribute access on ThemeOutput — no dict.get() on LLM output.
                theme_text = str(theme.theme or "").strip()
                # Convert to dict at the annotation boundary (response payload shape).
                theme_dict = theme.model_dump()
                annotated_themes.append(theme_dict)
                if not theme_text or not corpus:
                    theme_dict["verified"] = False
                    theme_dict["verification_reason"] = (
                        "empty theme text" if not theme_text else "no source corpus available"
                    )
                    unverified_themes.append(theme_dict)
                    continue
                try:
                    supported, match_score = await asyncio.to_thread(
                        _theme_supported, verifier, theme_text, corpus, chunks
                    )
                except Exception:
                    logger.warning("weekly_summary: theme verification raised", exc_info=True)
                    theme_dict["verified"] = False
                    theme_dict["verification_reason"] = "verifier raised an exception"
                    unverified_themes.append(theme_dict)
                    continue
                if supported:
                    theme_dict["verified"] = True
                    theme_dict["verification_reason"] = None
                    verified_themes.append(theme_dict)
                else:
                    theme_dict["verified"] = False
                    score_pct = (
                        f"{int(round(match_score * 100))}%"
                        if match_score is not None
                        else "no match"
                    )
                    theme_dict["verification_reason"] = (
                        f"theme text not supported by source papers (best fuzzy match: {score_pct})"
                    )
                    unverified_themes.append(theme_dict)

        result_topics.append(
            {
                "name": topic_name,
                "paper_count": len(papers),
                # Response boundary: JSON-serializable dicts annotated with
                # verified/verification_reason (same objects as the split lists).
                "themes": annotated_themes,
                "verified_themes": verified_themes,
                "unverified_themes": unverified_themes,
                "top_papers": top_papers,
                "summary": summary,
            }
        )

    return {
        "topics": result_topics,
        "total_papers": len(total_papers),
        "period_start": cutoff.isoformat(),
        "period_end": utc_now_iso(),
    }
